[tool.poetry]
name = "pythoneda-artifact-application-base"
version = "0.0.1a1"
description = "Application layer for pythoneda-artifact/base"
authors = ["rydnr <github@acm-sl.org>"]
readme = "README.md"
homepage = "https://github.com/pythoneda-artifact-application/base"
packages = [{include = "pythonedaartifactapplication"}]

[tool.poetry.dependencies]
python = "^3.8"
pythoneda-base = "^0.0.1a13"
pythoneda-artifact-base = "^0.0.1a1"
pythoneda-artifact-infrastructure-base = "^0.0.1a1"
pythoneda-application-base = "^0.0.1a9"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
